<?php
	$kek =$_POST['kek'];
	$classs =$_POST['classs'];
	$xp =$_POST['xp'];
	$back =$_POST['back'];
	$charn =$_POST['charn'];
	$race =$_POST['race'];
	$ali =$_POST['ali'];
	$stre =$_POST['stre'];
	$dex =$_POST['dex'];
	$consti =$_POST['consti'];
	$inte =$_POST['inte'];
	$wisd =$_POST['wisd'];
	$chari =$_POST['chari'];
	$strem =$_POST['strem'];
	$dexm =$_POST['dexm'];
	$constm =$_POST['constm'];
	$intem =$_POST['intem'];
	$wisdm =$_POST['wisdm'];
	$charim =$_POST['charim'];
	$stres =$_POST['stres'];
	$dexs =$_POST['dexs'];
	$constis =$_POST['constis'];
	$intes =$_POST['intes'];
	$wisds =$_POST['wisds'];
	$charis =$_POST['charis'];
	$proficiency =$_POST['proficiency'];
	$acrob =$_POST['acrob'];
	$anima =$_POST['anima'];
	$arcan =$_POST['arcan'];
	$athlet =$_POST['athlet'];
	$decep =$_POST['decep'];
	$histo=$_POST['histo'];
	$insig =$_POST['insig'];
	$intimi =$_POST['intimi'];
	$inve =$_POST['inve'];
	$medi =$_POST['medi'];
	$natu =$_POST['natu'];
	$perce =$_POST['perce'];
	$perf =$_POST['perf'];
	$persu =$_POST['persu'];
	$sleig =$_POST['sleig'];
	$stea =$_POST['stea'];
	$survi =$_POST['survi'];
	$passwis =$_POST['passwis'];
	$init =$_POST['init'];
	$speed =$_POST['speed'];
	$maxhit =$_POST['maxhit'];
	$hit =$_POST['hit'];
	$relig=$_POST['relig'];
	$armor=$_POST['armor'];
	$temphit =$_POST['temphit'];
	$hitdice =$_POST['hitdice'];
	$thitdice =$_POST['thitdice'];
	$proflang =$_POST['proflang'];
	$personal =$_POST['personal'];
	$ideal =$_POST['ideal'];
	$level =$_POST['level'];
	$bond =$_POST['bond'];
	$flaws =$_POST['flaws'];
	$featstrait =$_POST['featstrait'];
	$win =$_POST['win'];
	$failed =$_POST['failed'];
	$player=$_POST['player'];
	include 'db.php';
	$query = 'UPDATE players SET name=:kek,level=:level,experience=:experience,background=:background,charname=:charname,race=:race,alignment=:alignment,
	stre=:stre,dex=:dex,const=:consti,inte=:inte,wisd=:wisd,chari=:chari,strem=:strem,dexm=:dexm,constm=:constm,intem=:intem,wisdm=:wisdm,
	charim=:charim,stres=:stres,dexs=:dexs,consts=:constis,intes=:intes,wisds=:wisds,charis=:charis,proficiency=:proficiency,acrob=:acrob,
	anima=:anima,arcan=:arcan,athlet=:athlet,decep=:decep,histo=:histo,insig=:insig,intimi=:intimi,inve=:inve,medi=:medi,natu=:natu,
	perce=:perce,perf=:perf,persu=:persu,relig=:relig,sleig=:sleig,stea=:stea,survi=:survi,passwis=:passwis,armor=:armor,init=:init,
	speed=:speed,maxhit=:maxhit,hit=:hit,temphit=:temphit,hitdice=:hitdice,thitdice=:thitdice,proflang=:proflang,personal=:personal,
	ideal=:ideal,bond=:bond,flaws=:flaws,featstrait=:featstrait,savsuc=:win,savfail=:failed,classs=:classs
	WHERE id=:player';
	$stmt = $db->prepare($query);
	$stmt->bindParam(":kek",$kek );
	$stmt->bindParam(":classs",$classs );
	$stmt->bindParam(":level",$level);
	$stmt->bindParam(":experience",$xp );
	$stmt->bindParam(":background",$back );
	$stmt->bindParam(":charname",$charn );
	$stmt->bindParam(":race",$race );
	$stmt->bindParam(":alignment",$ali );
	$stmt->bindParam(":stre",$stre );
	$stmt->bindParam(":dex",$dex );
	$stmt->bindParam(":consti",$consti );
	$stmt->bindParam(":inte",$inte );
	$stmt->bindParam(":wisd",$wisd );
	$stmt->bindParam(":chari",$chari );
	$stmt->bindParam(":strem",$strem );
	$stmt->bindParam(":dexm",$dexm );
	$stmt->bindParam(":constm",$constm );
	$stmt->bindParam(":intem",$intem );
	$stmt->bindParam(":wisdm",$wisdm );
	$stmt->bindParam(":charim",$charim );
	$stmt->bindParam(":stres",$stres );
	$stmt->bindParam(":dexs",$dexs );
	$stmt->bindParam(":constis",$constis );
	$stmt->bindParam(":intes",$intes );
	$stmt->bindParam(":wisds",$wisds );
	$stmt->bindParam(":charis",$charis );
	$stmt->bindParam(":proficiency",$proficiency );
	$stmt->bindParam(":acrob",$acrob );
	$stmt->bindParam(":anima",$anima );
	$stmt->bindParam(":arcan",$arcan );
	$stmt->bindParam(":athlet",$athlet );
	$stmt->bindParam(":decep",$decep );
	$stmt->bindParam(":histo",$histo );
	$stmt->bindParam(":insig",$insig );
	$stmt->bindParam(":intimi",$intimi );
	$stmt->bindParam(":inve",$inve );
	$stmt->bindParam(":medi",$medi );
	$stmt->bindParam(":natu",$natu );
	$stmt->bindParam(":perce",$perce );
	$stmt->bindParam(":perf",$perf );
	$stmt->bindParam(":persu",$persu );
	$stmt->bindParam(":relig",$relig );
	$stmt->bindParam(":sleig",$sleig );
	$stmt->bindParam(":stea",$stea );
	$stmt->bindParam(":survi",$survi );
	$stmt->bindParam(":passwis",$passwis );
	$stmt->bindParam(":armor",$armor );
	$stmt->bindParam(":init",$init );
	$stmt->bindParam(":speed",$speed );
	$stmt->bindParam(":maxhit",$maxhit );
	$stmt->bindParam(":hit",$hit );
	$stmt->bindParam(":temphit",$temphit );
	$stmt->bindParam(":hitdice",$hitdice );
	$stmt->bindParam(":thitdice",$thitdice );
	$stmt->bindParam(":proflang",$proflang );
	$stmt->bindParam(":personal",$personal );
	$stmt->bindParam(":ideal",$ideal );
	$stmt->bindParam(":bond",$bond );
	$stmt->bindParam(":flaws",$flaws );
	$stmt->bindParam(":featstrait",$featstrait );
	$stmt->bindParam(":win",$win );
	$stmt->bindParam(":failed",$failed );
	$stmt->bindParam(":player",$player );
	$stmt->execute();
?>